### ISSUE TITLE
TSRestApiV2.auth_session_login does not support orgs

### ISSUE THREAD

**Issue by ms32035** [thoughtspot/thoughtspot_rest_api_v1_python#18]
There's no org_id parameter even though the endpoint supports it https://rest-api-sdk-v2-0.vercel.app/#/http/api-endpoints/authentication/login

**Comment by bryanthowell-ts** [comment]
Thank you for finding this, the fix will be in v1.6.1 available soon. You can use bearer token request pattern in the meantime to specify any org to log in to
